# Use this to pass in any parameters to the container
[build.env]
  passthrough = [
    "PKG_CONFIG_ALLOW_CROSS",
    "SODIUM_LIB_DIR",
    "SODIUM_INC_DIR",
  ]

# List the targets and choose a suitable container.
# This should work for ARM v6 targets, including the RaspberryPi 1 and Zero
[target.arm-unknown-linux-gnueabi]
  image = "avastmick/rust-cross-compile:arm-unknown-linux-gnueabi"

# This should work for ARM v7 targets, as well as all Raspbian installed Pis
[target.arm-unknown-linux-gnueabihf]
  image = "avastmick/rust-cross-compile:arm-unknown-linux-gnueabihf"
